version: '3'
services:
  mongo:
    image: "mongo:3.4"
  redis:
    image: "redis:alpine"
  user:
    build:
      context: ..
      dockerfile: docker/user.Dockerfile
  tweet:
    build:
      context: ..
      dockerfile: docker/tweet.Dockerfile
  follow:
    build:
      context: ..
      dockerfile: docker/follow.Dockerfile
    depends_on:
      - redis
  timeline:
    build:
      context: ..
      dockerfile: docker/timeline.Dockerfile
    depends_on:
      - mongo
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/tmp/default.conf
      - ../frontend/build:/html:ro
    depends_on:
      - user
      - follow
      - tweet
      - timeline
    ports:
      - "8080:8080"
    environment:
      - NGINX_PORT=8080
    command: /bin/bash -c "envsubst '$$NGINX_PORT' < /tmp/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
